// double-cta/src/double-cta.vue
<script>
import '../../tailwind';
export default {
  props: {
    primaryText: { type: String, required: false },
    primaryHref: { type: String, required: false },
    primaryOnClick: { type: Function, required: false },
    secondaryText: { type: String, required: false },
    secondaryHref: { type: String, required: false },
    secondaryOnClick: { type: Function, required: false },
  },
};
</script>
<template>
  <div class="flex mt-8 space-x-2">
    <a v-if="primaryHref" class="btn-primary" :href="primaryHref">
      {{ primaryText }}
    </a>
    <button v-else class="btn-primary" :onclick="primaryOnClick">
      {{ primaryText }}
    </button>
    <a v-if="secondaryHref" class="btn-text" :href="secondaryHref">
      {{ secondaryText }}
    </a>
    <button v-else class="btn-text" :onclick="secondaryOnClick">
      {{ secondaryText }}
    </button>
  </div>
</template>

// double-cta/src/DoubleCta.svelte
<script>
  export let primaryText;
  export let primaryHref;
  export let primaryOnClick;
  export let secondaryText;
  export let secondaryHref;
  export let secondaryOnClick;
</script>

<div class="flex mt-8 space-x-2">
  {#if !!primaryHref}
    <a class="btn-primary" href={primaryHref}>{primaryText}</a>
  {:else}
    <button class="btn-primary" onClick={primaryOnClick}>
      {primaryText}
    </button>
  {/if}
  {#if !!secondaryHref}
    <a class="btn-text" href={secondaryHref}>{secondaryText}</a>
  {:else}
    <button class="btn-text" onClick={secondaryOnClick}>
      {secondaryText}
    </button>
  {/if}
</div>
