// double-cta/src/DoubleCta.tsx
import React from 'react';

export type DoubleCtaProps = {
	primaryText: string;
	primaryHref?: string;
	primaryOnClick?: Function;
	secondaryText: string;
	secondaryHref?: string;
	secondaryOnClick?: Function;
};

export const DoubleCtaReact = ({ primaryText, primaryHref, primaryOnClick, secondaryText, secondaryHref, secondaryOnClick }: DoubleCtaProps) => (
	<div className="flex mt-8 space-x-2">
		{!!primaryHref
			? <a className="btn-primary" href={primaryHref}>{primaryText}</a>
			: <button className="btn-primary" onClick={primaryOnClick}>{primaryText}</button>
		}
		{!!secondaryHref
			? <a className="btn-text" href={secondaryHref}>{secondaryText}</a>
			: <button className="btn-text" onClick={secondaryOnClick}>{secondaryText}</button>
		}
	</div>
);

// double-cta/src/DoubleCta.svelte
<script>
  export let primaryText;
  export let primaryHref;
  export let primaryOnClick;
  export let secondaryText;
  export let secondaryHref;
  export let secondaryOnClick;
</script>

<div class="flex mt-8 space-x-2">
  {#if !!primaryHref}
    <a class="btn-primary" href={primaryHref}>{primaryText}</a>
  {:else}
    <button class="btn-primary" onClick={primaryOnClick}>
      {primaryText}
    </button>
  {/if}
  {#if !!secondaryHref}
    <a class="btn-text" href={secondaryHref}>{secondaryText}</a>
  {:else}
    <button class="btn-text" onClick={secondaryOnClick}>
      {secondaryText}
    </button>
  {/if}
</div>
